### ISSUE TITLE
Coroutines not supported ?

### ISSUE THREAD

**Issue by MaksymSofer** [alexmojaki/birdseye#103] opened 2023-10-15 16:54 UTC
Using the latest 0.9.4, Birdseye telling me that coroutines are not supported.
Any work on support?

**Comment by alexmojaki** [comment] 2023-10-16 20:24
Closing as duplicate of https://github.com/alexmojaki/birdseye/issues/78

While I'll still fix bugs in this package, I'm not doing any major work on it, so any support will have to come from a PR

**Closed by alexmojaki** 2023-10-16 20:24 UTC
